name: 'Shared Setup'
description: 'Node.js setup, caching y vercel CLI para Next.js'
inputs:
  node-version:
    description: 'Node version'
    required: false
    default: '22'
  cache-key:
    description: 'Cache key suffix'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        
    - name: Cache Next.js
      uses: actions/cache@v4
      with:
        path: |
          .next/cache
          node_modules/.cache/turbo
          **/node_modules/.cache
        key: ${{ runner.os }}-next-${{ inputs.cache-key }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-next-${{ inputs.cache-key }}-
          
    - name: Install dependencies
      shell: bash
      run: |
        corepack enable
        npm ci --frozen-lockfile
        
    - name: Install Vercel CLI
      shell: bash
      run: npm i -g vercel@latest
