name: 'Shared Setup'
description: 'Node.js setup, caching y vercel CLI para Next.js'
inputs:
  node-version:
    default: '20'
  cache-key:
    default: ''
runs:
  using: 'composite'
  steps:
  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: ${{ inputs.node-version }}

  - name: Setup Bun
    uses: oven-sh/setup-bun@v2
    with:
      bun-version: latest

  - name: Cache .bun-install
    uses: actions/cache@v4
    with:
      path: |
        .bun-install/cache
        .next/cache
      key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
      restore-keys: ${{ runner.os }}-bun-

  - name: Install dependencies
    shell: bash
    run: bun install


